//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaemonMouse.ServiceMouse {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="ServiceMouse.MouseSoap")]
    public interface MouseSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/SendMousePosition", ReplyAction="*")]
        void SendMousePosition(double tx, double ty, double tz, double rx, double ry, double rz, double angle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/SendMousePosition", ReplyAction="*")]
        System.Threading.Tasks.Task SendMousePositionAsync(double tx, double ty, double tz, double rx, double ry, double rz, double angle);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MouseSoapChannel : DaemonMouse.ServiceMouse.MouseSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MouseSoapClient : System.ServiceModel.ClientBase<DaemonMouse.ServiceMouse.MouseSoap>, DaemonMouse.ServiceMouse.MouseSoap {
        
        public MouseSoapClient() {
        }
        
        public MouseSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MouseSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MouseSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MouseSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendMousePosition(double tx, double ty, double tz, double rx, double ry, double rz, double angle) {
            base.Channel.SendMousePosition(tx, ty, tz, rx, ry, rz, angle);
        }
        
        public System.Threading.Tasks.Task SendMousePositionAsync(double tx, double ty, double tz, double rx, double ry, double rz, double angle) {
            return base.Channel.SendMousePositionAsync(tx, ty, tz, rx, ry, rz, angle);
        }
    }
}
